REPO_TAGLINE: Humanities • social sciences • critical thinking
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: peace
SITE_URL: https://academic-codex.github.io/SAP0679-Humanidades-e-Ciencias-Sociais

BG_1: "#2A0F45"
BG_2: "#3A1768"
TEXT_MAIN: "#F5E9FF"
TEXT_MUTED: "#D3BDF0"
ACCENT: "#C77DFF"
CARD_RADIUS: "18"