TITLE_1: SAP0679
TITLE_2: Humanidades e Ciências Sociais
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro A …</li>
    <li>Artigo B …</li>
  </ul>

CONTACT_NAME: Nara Avila
CONTACT_EMAIL: nara.moraes@usp.br
GITHUB_LINK: https://github.com/Academic-Codex/SAP0679-Humanidades-e-Ciencias-Sociais

# hero: você pode apontar um path relativo do repo de imagens global
# ou um URL absoluto. Se for relativo, o build compõe o caminho.
ASSETS_BASE: https://academic-codex.github.io
ASSETS_SUBDIR: img/portfolio
HERO_FILE: ciencias-sociais.png
# Opcional: passe um URL direto e ele tem prioridade
HERO_URL: # ex.: https://…/img/portfolio/ciencias-sociais.jpg
