TITLE_1: SAP0679
TITLE_2: Humanidades e Ciências Sociais
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro AA …</li>
    <li>Artigo BB …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SAP0679-Humanidades-e-Ciencias-Sociais

HERO_FILE: ciencias-sociais.png
